version: v1
description: Workflow to make a pretty picture

steps:
  - name: 1-1
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-2
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-3
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-4
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-5
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: Step-2-Notify-team
    description: ""
    image: alpine:latest
    input:
      - echo "Hello world. I am Step 2"
      - sleep 2
    dependsOn:
      - 1-1
