version: v1
description: Workflow to make a pretty picture

steps:
  - name: 1-1
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-2
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-3
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-4
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-5
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-6
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 2-1
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 1-1
  - name: 2-2
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 1-2
  - name: 2-3
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 1-3
  - name: 2-4
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 1-4
  - name: 2-5
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 1-5
  - name: 2-6
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 1-6
  - name: Step-2-Notify-team
    description: ""
    image: alpine:latest
    input:
      - echo "Hello world. I am Step 2"
      - sleep 2
    dependsOn:
      - 1-1
