version: v1
description: Workflow to make a pretty picture

steps:
  - name: 1-1
    description: ""
    image: alpine:latest
    input:
      - sleep 5
      - exit 1
  - name: 1-2
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-3
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-4
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 1-5
    description: ""
    image: alpine:latest
    input:
      - sleep 5
      - exit 1
  - name: 1-6
    description: ""
    image: alpine:latest
    input:
      - sleep 5
  - name: 2-1
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 1-1
  - name: 2-2
    description: ""
    image: alpine:latest
    input:
      - sleep 5
      - exit 1
    dependsOn:
      - 1-2
  - name: 2-3
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 1-3
  - name: 2-4
    description: ""
    image: alpine:latest
    input:
      - sleep 5
      - exit 1
    dependsOn:
      - 1-4
  - name: 2-5
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 1-5
  - name: 2-6
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 1-6
  - name: 3-1
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 2-1asd
  - name: 3-2
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 2-2
  - name: 3-3
    description: ""
    image: alpine:latest
    input:
      - sleep 5
      - exit 1
    dependsOn:
      - 2-3
  - name: 3-4
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 2-4
  - name: 3-5
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 2-5
  - name: 3-6
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 2-6

  - name: 4-1
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 3-1
  - name: 4-2
    description: ""
    image: alpine:latest
    input:
      - sleep 5
      - exit 1
    dependsOn:
      - 3-2
  - name: 4-3
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 3-3
  - name: 4-4
    description: ""
    image: alpine:latest
    input:
      - sleep 5
      - exit 1
    dependsOn:
      - 3-4
  - name: 4-5
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 3-5
  - name: 4-6
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 3-6

  - name: 5-1
    description: ""
    image: alpine:latest
    input:
      - sleep 5
      - exit 1
    dependsOn:
      - 4-1
  - name: 5-2
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 4-2
  - name: 5-3
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 4-3
  - name: 5-4
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 4-4
  - name: 5-5
    description: ""
    image: alpine:latest
    input:
      - sleep 5
      - exit 1
    dependsOn:
      - 4-5
  - name: 5-6
    description: ""
    image: alpine:latest
    input:
      - sleep 5
    dependsOn:
      - 4-6
